"""
NEXUS MVP — single-file backend.

Endpoints:
  GET  /              → serves the tablet UI
  GET  /health        → health check
  WS   /stream        → receives raw PCM audio, streams transcript events back
  POST /chat          → chatbot Q&A against the accumulated transcript
  DELETE /session/{id} → clears a session transcript

Run:
  python server.py
  (or: uvicorn server:app --host 0.0.0.0 --port 8000 --reload)
"""

import asyncio
import os
import uuid
from collections import defaultdict
from pathlib import Path

import azure.cognitiveservices.speech as speechsdk
from dotenv import load_dotenv
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from openai import AsyncAzureOpenAI
from pydantic import BaseModel

load_dotenv()

# ── Azure config (required) ───────────────────────────────────────────────────
SPEECH_KEY    = os.environ["AZURE_SPEECH_KEY"]
SPEECH_REGION = os.environ["AZURE_SPEECH_REGION"]
OAI_ENDPOINT  = os.environ["AZURE_OPENAI_ENDPOINT"]
OAI_KEY       = os.environ["AZURE_OPENAI_API_KEY"]
OAI_DEPLOY    = os.environ.get("AZURE_OPENAI_DEPLOYMENT", "gpt-4o")
OAI_VERSION   = os.environ.get("AZURE_OPENAI_API_VERSION", "2024-05-01-preview")

# ── In-memory stores (per session, cleared on disconnect or explicit delete) ───
#   transcripts : session_id → [utterance, ...]
#   chat_history: session_id → [{"role": ..., "content": ...}, ...]
transcripts:   dict[str, list[str]]              = defaultdict(list)
chat_history:  dict[str, list[dict]]             = defaultdict(list)

# ── Azure OpenAI client ───────────────────────────────────────────────────────
oai = AsyncAzureOpenAI(
    azure_endpoint=OAI_ENDPOINT,
    api_key=OAI_KEY,
    api_version=OAI_VERSION,
)

# ── App ───────────────────────────────────────────────────────────────────────
app = FastAPI(title="NEXUS MVP", docs_url="/docs")
app.mount("/static", StaticFiles(directory="static"), name="static")


@app.get("/", include_in_schema=False)
async def index():
    return HTMLResponse(Path("static/index.html").read_text(encoding="utf-8"))


@app.get("/health")
async def health():
    return {"status": "ok"}


# ── Chat ──────────────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    session_id: str
    message: str


@app.post("/chat")
async def chat(req: ChatRequest):
    transcript_text = "\n".join(transcripts.get(req.session_id, []))

    system_prompt = (
        "You are NEXUS, an AI assistant analysing a live conversation.\n"
        "Answer the user's questions using the transcript below as your source of truth.\n"
        "Be direct and concise. Use bullet points when listing multiple items.\n"
        "If the answer is not in the transcript, say so clearly.\n"
        "The transcript may contain Greek and English — handle both.\n\n"
        f"TRANSCRIPT:\n{transcript_text or '(no transcript yet — recording may not have started)'}"
    )

    history = chat_history[req.session_id]

    # Build the message list: system + conversation history + new user message
    messages = [{"role": "system", "content": system_prompt}]
    messages.extend(history)
    messages.append({"role": "user", "content": req.message})

    response = await oai.chat.completions.create(
        model=OAI_DEPLOY,
        messages=messages,
        temperature=0.3,
        max_tokens=1024,
    )

    assistant_reply = response.choices[0].message.content or ""

    # Store conversation turn for follow-up context
    history.append({"role": "user",      "content": req.message})
    history.append({"role": "assistant", "content": assistant_reply})

    # Keep history bounded (last 20 turns = 40 messages)
    if len(history) > 40:
        chat_history[req.session_id] = history[-40:]

    return {"response": assistant_reply}


@app.delete("/session/{session_id}")
async def clear_session(session_id: str):
    transcripts.pop(session_id, None)
    chat_history.pop(session_id, None)
    return {"cleared": True}


# ── Audio WebSocket ───────────────────────────────────────────────────────────
#
# Query params:
#   session_id  — UUID generated by the client on page load
#   lang        — "auto" (default), "el-GR", or "en-US"
#
# Frame format: binary frames = raw PCM, 16-bit LE, mono, 16 kHz
# Text frames:  {"type": "ping"} → server replies {"type": "pong"}
#
# Server emits JSON events:
#   {"type": "interim", "text": "..."}
#   {"type": "final",   "text": "...", "lang": "el-GR", "session_id": "..."}
#   {"type": "error",   "message": "..."}

@app.websocket("/stream")
async def audio_stream(websocket: WebSocket):
    await websocket.accept()

    session_id = websocket.query_params.get("session_id") or str(uuid.uuid4())
    lang_mode  = websocket.query_params.get("lang", "auto")

    loop  = asyncio.get_event_loop()
    queue: asyncio.Queue[dict | None] = asyncio.Queue()

    # ── Azure Speech setup ────────────────────────────────────────────────────
    speech_config = speechsdk.SpeechConfig(
        subscription=SPEECH_KEY,
        region=SPEECH_REGION,
    )
    speech_config.set_profanity(speechsdk.ProfanityOption.Raw)
    speech_config.request_word_level_timestamps()

    audio_format = speechsdk.audio.AudioStreamFormat(
        samples_per_second=16000,
        bits_per_sample=16,
        channels=1,
    )
    push_stream  = speechsdk.audio.PushAudioInputStream(stream_format=audio_format)
    audio_config = speechsdk.audio.AudioConfig(stream=push_stream)

    if lang_mode == "auto":
        # Continuous language detection between Greek and English
        auto_detect = speechsdk.languageconfig.AutoDetectSourceLanguageConfig(
            languages=["el-GR", "en-US"]
        )
        recognizer = speechsdk.SpeechRecognizer(
            speech_config=speech_config,
            auto_detect_source_language_config=auto_detect,
            audio_config=audio_config,
        )
    else:
        speech_config.speech_recognition_language = lang_mode
        recognizer = speechsdk.SpeechRecognizer(
            speech_config=speech_config,
            audio_config=audio_config,
        )

    # ── SDK callbacks (run on Azure Speech SDK thread) ────────────────────────

    def _put(event: dict | None) -> None:
        loop.call_soon_threadsafe(queue.put_nowait, event)

    def on_recognizing(evt: speechsdk.SpeechRecognitionEventArgs) -> None:
        if evt.result.text:
            _put({"type": "interim", "text": evt.result.text})

    def on_recognized(evt: speechsdk.SpeechRecognitionEventArgs) -> None:
        if evt.result.reason != speechsdk.ResultReason.RecognizedSpeech:
            return
        if not evt.result.text:
            return

        detected_lang = None
        if lang_mode == "auto":
            try:
                r = speechsdk.AutoDetectSourceLanguageResult(evt.result)
                detected_lang = r.language   # e.g. "el-GR" or "en-US"
            except Exception:
                pass

        transcripts[session_id].append(evt.result.text)
        _put({
            "type":       "final",
            "text":       evt.result.text,
            "lang":       detected_lang,
            "session_id": session_id,
        })

    def on_stopped(_evt) -> None:
        _put(None)  # sentinel — signals the send loop to stop

    def on_canceled(evt: speechsdk.SpeechRecognitionCanceledEventArgs) -> None:
        _put({
            "type":    "error",
            "message": f"Recognition cancelled: {evt.cancellation_details.error_details}",
        })
        _put(None)

    recognizer.recognizing.connect(on_recognizing)
    recognizer.recognized.connect(on_recognized)
    recognizer.session_stopped.connect(on_stopped)
    recognizer.canceled.connect(on_canceled)

    recognizer.start_continuous_recognition()

    # ── Event broadcaster — drains queue → sends to client ───────────────────

    async def send_events() -> None:
        while True:
            event = await queue.get()
            if event is None:
                return
            try:
                await websocket.send_json(event)
            except Exception:
                return

    send_task = asyncio.create_task(send_events())

    # ── Receive audio from client ─────────────────────────────────────────────
    try:
        while True:
            message = await websocket.receive()
            if message["type"] == "websocket.disconnect":
                break
            if message.get("bytes"):
                push_stream.write(message["bytes"])
            elif message.get("text"):
                import json
                ctrl = json.loads(message["text"])
                if ctrl.get("type") == "ping":
                    await websocket.send_json({"type": "pong"})

    except WebSocketDisconnect:
        pass
    finally:
        push_stream.close()
        await loop.run_in_executor(None, recognizer.stop_continuous_recognition)
        queue.put_nowait(None)
        send_task.cancel()


# ── Dev entrypoint ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("server:app", host="0.0.0.0", port=8000, reload=True)
